In [ ]:
import yfinance as yf

In [ ]:
sp500 = yf.download("^GSPC", start="2016-01-01", end="2026-01-01")
sp500.to_csv("sp500.csv")

/tmp/ipykernel_16223/3205265358.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sp500 = yf.download("^GSPC", start="2016-01-01", end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

In [ ]:
stoxx = yf.download("^STOXX", start="2016-01-01", end="2026-01-01")
stoxx.to_csv("stoxx600.csv")

/tmp/ipykernel_16223/1846886321.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stoxx = yf.download("^STOXX", start="2016-01-01", end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

In [ ]:
ShanghaiComp = yf.download("000001.SS", start="2016-01-01", end="2026-01-01")
ShanghaiComp.to_csv("ShanghaiComp.csv")

/tmp/ipykernel_16223/3693072570.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  ShanghaiComp = yf.download("000001.SS", start="2016-01-01", end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

In [1]:
import pandas as pd

In [ ]:
SP500 = pd.read_csv("sp500.csv")

In [ ]:
SP500 = SP500.iloc[2:].copy()
SP500.columns = ["Date", "Close", "High", "Low", "Open", "Volume"]
SP500.reset_index(drop=True, inplace=True)

SP500["Date"] = pd.to_datetime(SP500["Date"])
SP500 = SP500.astype({
    "Close": float,
    "High": float,
    "Low": float,
    "Open": float,
    "Volume": float
})

In [ ]:
STOXX600 = pd.read_csv("stoxx600.csv")

In [ ]:
STOXX600 = STOXX600.iloc[2:].copy()
STOXX600.columns = ["Date", "Close", "High", "Low", "Open", "Volume"]
STOXX600.reset_index(drop=True, inplace=True)

STOXX600["Date"] = pd.to_datetime(STOXX600["Date"])
STOXX600 = STOXX600.astype({
    "Close": float,
    "High": float,
    "Low": float,
    "Open": float,
    "Volume": float
})

In [ ]:
ShanghaiComp = pd.read_csv("ShanghaiComp.csv")

In [ ]:
ShanghaiComp = ShanghaiComp.iloc[2:].copy()
ShanghaiComp.columns = ["Date", "Close", "High", "Low", "Open", "Volume"]
ShanghaiComp.reset_index(drop=True, inplace=True)

ShanghaiComp["Date"] = pd.to_datetime(ShanghaiComp["Date"])
ShanghaiComp = ShanghaiComp.astype({
    "Close": float,
    "High": float,
    "Low": float,
    "Open": float,
    "Volume": float
})

In [ ]:
SP500.describe()

,Date,Close,High,Low,Open,Volume
count,2514,2514.000000,2514.000000,2514.000000,2514.000000,2.514000e+03
mean,2020-12-30 09:28:46.968973568,3770.420754,3789.841542,3748.132206,3769.783358,4.151839e+09
min,2016-01-04 00:00:00,1829.079956,1847.000000,1810.099976,1833.400024,0.000000e+00
25%,2018-07-02 06:00:00,2711.787476,2729.302551,2697.327454,2712.830078,3.500355e+09
50%,2020-12-29 12:00:00,3676.395020,3705.280029,3645.855103,3683.665039,3.922175e+09
75%,2023-06-29 18:00:00,4514.057373,4532.042358,4494.827637,4512.690063,4.598322e+09
max,2025-12-31 00:00:00,6932.049805,6945.770020,6921.600098,6936.020020,9.976520e+09
std,NaN,1292.637990,1298.569769,1285.870346,1292.474148,1.028491e+09

In [ ]:
STOXX600.describe()

,Date,Close,High,Low,Open,Volume
count,2513,2513.000000,2513.000000,2513.000000,2513.000000,2.513000e+03
mean,2020-12-29 09:15:15.399920384,424.647843,426.723283,422.390255,424.575607,2.147798e+08
min,2016-01-04 00:00:00,279.660004,288.220001,268.570007,277.510010,0.000000e+00
25%,2018-07-02 00:00:00,374.329987,376.089996,372.799988,374.440002,1.732141e+08
50%,2021-01-05 00:00:00,407.869995,410.390015,405.670013,408.559998,2.014763e+08
75%,2023-06-28 00:00:00,467.350006,469.109985,464.850006,467.140015,2.383166e+08
max,2025-12-30 00:00:00,592.780029,593.419983,588.780029,588.859985,1.109144e+09
std,NaN,66.227174,66.149290,66.248491,66.155606,7.678845e+07

In [ ]:
ShanghaiComp.describe()

,Date,Close,High,Low,Open,Volume
count,2428,2428.000000,2428.000000,2428.000000,2428.000000,2.428000e+03
mean,2020-12-31 18:28:28.072487680,3181.896756,3199.316934,3160.208302,3179.433552,2.943317e+05
min,2016-01-04 00:00:00,2464.363037,2488.479004,2440.906982,2446.019043,1.000000e+02
25%,2018-07-01 06:00:00,2979.063965,2998.262207,2959.108704,2978.697327,1.826750e+05
50%,2020-12-29 12:00:00,3184.969482,3197.588013,3162.392944,3183.140503,2.711000e+05
75%,2023-07-04 06:00:00,3364.462402,3382.257996,3345.832031,3364.106995,3.618500e+05
max,2025-12-31 00:00:00,4029.500977,4034.079102,3994.770996,4023.876953,1.313500e+06
std,NaN,285.660677,285.385466,285.845569,285.815458,1.444735e+05

In [4]:
stooq_SP500 = pd.read_csv("SP500_stooq.csv")
stooq_SP500.columns = ["Date", "Open", "High", "Low", "Close", "Volume"]

In [5]:
stooq_SP500.head()

         Date     Open     High      Low    Close        Volume
0  2016-01-04  2038.20  2038.20  1989.68  2012.66  2.391600e+09
1  2016-01-05  2013.78  2021.94  2004.17  2016.71  2.059233e+09
2  2016-01-06  2011.71  2011.71  1979.05  1990.26  2.409256e+09
3  2016-01-07  1985.32  1985.32  1938.83  1943.09  2.820328e+09
4  2016-01-08  1945.97  1960.40  1918.46  1922.03  2.591633e+09

In [7]:
stooq_DAX = pd.read_csv("GermanDAX_stooq.csv")
stooq_DAX.columns = ["Date", "Open", "High", "Low", "Close", "Volume"]

In [8]:
stooq_DAX.head()

         Date      Open      High       Low     Close     Volume
0  2016-01-04  10485.81  10485.91  10248.58  10283.44  119844268
1  2016-01-05  10373.27  10384.26  10173.52  10310.10   84890443
2  2016-01-06  10288.68  10288.68  10094.18  10214.02   90465727
3  2016-01-07  10144.17  10145.47   9810.47   9979.85  128029005
4  2016-01-08  10010.47  10122.46   9849.34   9849.34   98631078

In [10]:
SSEComp_stooq = pd.read_csv("SSEComposite_stooq.csv")
SSEComp_stooq.columns = ["Date", "Open", "High", "Low", "Close", "Volume"]

In [11]:
SSEComp_stooq.head()

         Date     Open     High      Low    Close  Volume
0  2016-01-04  3536.59  3538.69  3295.74  3296.26       0
1  2016-01-05  3196.65  3328.14  3189.61  3287.71       0
2  2016-01-06  3291.20  3362.97  3288.93  3361.84       0
3  2016-01-07  3309.66  3309.66  3115.89  3125.00       0
4  2016-01-08  3194.63  3235.45  3056.88  3186.41       0

In [12]:
Apple_stooq = pd.read_csv("Apple.inc_stooq.csv")
Apple_stooq.columns = ["Date", "Open", "High", "Low", "Close", "Volume"]

In [13]:
Apple_stooq.head()

         Date     Open     High      Low    Close     Volume
0  2016-01-04  23.1136  23.7397  22.9793  23.7347  278921861
1  2016-01-05  23.8201  23.8448  23.0697  23.1365  234060370
2  2016-01-06  22.6524  23.0607  22.4958  22.6841  298533216
3  2016-01-07  22.2287  22.5545  21.7224  21.7263  340144808
4  2016-01-08  22.2002  22.3257  21.7959  21.8402  308853529

In [14]:
AMD_stooq = pd.read_csv("AMD_us_stooq.csv")
AMD_stooq.columns = ["Date", "Open", "High", "Low", "Close", "Volume"]

In [15]:
AMD_stooq.head()

         Date  Open   High   Low  Close    Volume
0  2016-01-04  2.77  2.820  2.63  2.770  31607294
1  2016-01-05  2.77  2.800  2.64  2.750  12807364
2  2016-01-06  2.66  2.710  2.47  2.505  21880786
3  2016-01-07  2.43  2.480  2.26  2.275  21530043
4  2016-01-08  2.36  2.425  2.10  2.140  31296413

In [16]:
NVIDIA_stooq = pd.read_csv("NVIDIA_Corp_stooq.csv")
NVIDIA_stooq.columns = ["Date", "Open", "High", "Low", "Close", "Volume"]

In [17]:
NVIDIA_stooq.head()

         Date      Open      High       Low     Close     Volume
0  2016-01-04  0.787894  0.794874  0.781733  0.789852  334396382
1  2016-01-05  0.804690  0.815942  0.792936  0.802462  409964669
2  2016-01-06  0.789392  0.792936  0.760295  0.769331  402251715
3  2016-01-07  0.750040  0.755254  0.729103  0.738777  586979770
4  2016-01-08  0.748343  0.749060  0.721362  0.722960  378002116